name: Daily Odds Parsing

on:
  schedule:
    - cron: '1 0 * * *'  # This runs at 00:01 UTC every day

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run odds parsing script
      run: python src/odds_parsing/parse_odds.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/data.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update data.csv" && git push)